### ISSUE TITLE
automatically remove redundant notes

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#66] opened 2017-02-09 12:57 UTC
In case one note is no longer connected to any picture, this note cannot be found by viewing any picture. But currently it could still be viewed in the recent note list. 

Possible solution: 
(1) once the activity recent note list is called, check all the notes whether they are still attached to any picture and remove the redundant notes. This might have performance issue if user has too many notes and pictures.

**Comment by soultice** [comment] 2017-02-27 11:17
This should be fixed in 324a6f19b1ee8fdfc48dc821cfb41ba752219367.
(In file RecentNoteActivity.java)
Unfortunately until tomorrow I have little time to test if the issue is resolved.

Additionally, as you correctly mentioned, the performance might be poor for a high count of pictures.
Suggestion: Define Notes in the database with attached pictures ID, if the field is empty -> delete.

**Comment by soultice** [comment] 2017-02-27 11:18
Closing for now

**Closed by soultice** 2017-02-27 11:18 UTC
Labels: bug
