### ISSUE TITLE
Selection list of collection broken after #74

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#75] opened 2017-02-22 15:45 UTC
Testserver: qa-gluons
Test date: 22.02.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: select collection for manual upload
after the described situation in #74 the collection list was
- unsorted 
- selected collection displayed twice
- author of all available collections changed to "some cool guy" (this issue came up several times, but not reproducable)

Observation:
![coll_selection](https://cloud.githubusercontent.com/assets/14921701/23218896/d7164582-f91d-11e6-9b08-0a74e483f76c.JPG)

**Comment by tonyqd** [comment] 2017-02-27 13:38
cannot reproduce it on gluons(also never encounter this problem on gluons server )

**Comment by soultice** [comment] 2017-02-27 18:40
Seemingly this issue is caused in the file SettingsListAdapter.java  
The default string value of the View shows "Some Cool Guy", it is not overridden if the contributor returns null.

**Comment by soultice** [comment] 2017-02-27 20:27
This should be addressed in cfbede780182789574531ab892979186e25f0ee7, testing tommorow

**Comment by soultice** [comment] 2017-02-28 10:45
As the exact reason cannot be reproduced but I am fairly sure the problem is fixed I'm closing.

**Closed** 2017-03-01 09:48 UTC
Labels: bug
